sonar.projectKey=Backend
sonar.projectName=Backend
sonar.sources=./
sonar.language=ts
sonar.host.url=http://localhost:9000
sonar.token=sqp_c8fb81b49fa6a4dbb16157c28a37aa370bc7af27
sonar.javascript.lcov.reportPaths=coverage/lcov.info