export default {
  API_ENVIRONMENT: "PROD",
  API_NAME: "API TYPESCRIPT",
  API_PORT: 3500,
  API_VERSION: "1.0.0",
  API_SECRET_KEY: "*FIDOC_2025*",
  API_CORS: "*,localhost,localhost:4200", // lista de cors se separan por una coma
  API_DEBUG: false,
  SWAGGER_ENVIRONMENT: "PROD",
  SWAGGER_TITLE: "API",
  SWAGGER_HOST: 'localhost:3500',
  SWAGGER_BASE_PATH: '/api',
  SWAGGER_EMAIL: 'juan.ruiz@leon.gob.mx',
  POSTGRESQL_ENVIRONMENT: "PROD",
  POSTGRESQL_URL: "postgresql://postgres.ygsmdqeaaztpnagtviao:Ezequielpitufo1*@aws-0-us-west-2.pooler.supabase.com:6543/postgres",
  POSTGRESQL_HOST: "aws-0-us-west-2.pooler.supabase.com",
  POSTGRESQL_PORT: "6543",
  POSTGRESQL_USER_NAME: "postgres.ygsmdqeaaztpnagtviao",
  POSTGRESQL_USER_PASSWORD: "Ezequielpitufo1*",
  POSTGRESQL_DATABASE: "postgres",
  SECRETORPRIVATEKEY: "Est03sMyPublick3y23@913",
  RESEND_API_KEY: "re_htyyqq6h_CyyGzB3MteatA3dHEhoBMbwo",
  MAILERSEND_API_KEY: "mlsn.307509db207589fe33d2b991b2e81db4521ae410c6f8eb985a1aa719f3b75968",
  IP: 'https://sgp-ws-2025.onrender.com'
};
